services:
  minio:
    image: minio/minio:latest
    container_name: minio-feature-store
    restart: unless-stopped
    ports:
      - "9100:9000"  # API
      - "9101:9001"  # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-mc:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: |
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb local/store-item-demand-forecasting --ignore-existing;
      exit 0;
      "

volumes:
  minio-storage:
    driver: local

networks:
  default:
    name: feature-store-network